app:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
axon:
  axonserver:
    servers: localhost:${AXON_PORT}
  serializer:
    general: jackson
    events: jackson
    messages: jackson
logging.level:
  io.dabrowa: DEBUG
